// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCZku6oz0CmnnvgLAZLwRYtJNj0hc1Ltwo",
    authDomain: "ridemate-afd1e.firebaseapp.com",
    projectId: "ridemate-afd1e",
    storageBucket: "ridemate-afd1e.firebasestorage.app",
    messagingSenderId: "975273579439",
    appId: "1:975273579439:web:0734372517988c97abd55a",
    measurementId: "G-3Z59S7QDTQ",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM12GcjelsABkd45Vtp5PugbbbsRONgsA',
    appId: '1:975273579439:android:16b1378c049bae41abd55a',
    messagingSenderId: '975273579439',
    projectId: 'ridemate-afd1e',
    storageBucket: 'ridemate-afd1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXWy9R0JbkZ8C8tmr3MtchvCkoQZNCQaQ',
    appId: '1:975273579439:ios:584823da4d281c1babd55a',
    messagingSenderId: '975273579439',
    projectId: 'ridemate-afd1e',
    storageBucket: 'ridemate-afd1e.firebasestorage.app',
    iosBundleId: 'ride.mate',
  );
}
